Myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.conf.urls.static import static
from mylife import views as mylife_views
from aboutme import views as aboutme_views
from message import views as message_views
from . import  man_urls
from django.contrib.auth import views as auth_views
import django_comments
urlpatterns = [
    url(r'^$', mylife_views.showHome, name='showHome'),
    url(r'^mylife/', include('mylife.urls')),
    url(r'^aboutme/', include('aboutme.urls')),
    url(r'^message/', include('message.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^man/', include(man_urls)),
    url(r'^login/', aboutme_views.login_man, name='login_man'),
    url(r'^login/', auth_views.login),
    url(r'^comments/', include('django_comments.urls')),
]+ static(settings.STATIC_URL) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views as message_views

urlpatterns = [
    url(r'^showmessage/$', message_views.showmessage, name='showmessage'),
    # url(r'^lifelist/$', message_views.lifelist, name='lifelist'),
]

aboutme/models.py
from django.db import models
import os, uuid
from django.db.models.fields.related import ForeignKey

# Create your models here.

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('avatar', filename)

class Myself(models.Model):
    user_name = models.CharField(max_length=30)
    introduce = models.CharField(max_length=100)
    content = models. TextField(max_length=500)
    avatar = models.ImageField(upload_to=get_file_path, blank=True)
    qq_number = models.CharField(max_length=30)
    job_post = models.CharField(max_length=30)
    work_time = models.DateField(blank=True, null=True)
    university = models.CharField(max_length=30)
    education_background = models.CharField(max_length=30)

class Technical(models.Model):
    name = models.CharField(max_length=30)
    introduce = models.CharField(max_length=100,blank=True,null=True)
    def __str__(self):
         return self.name

class UseTechnial(models.Model):
    myself = ForeignKey(Myself, on_delete=models.CASCADE)
    technical = ForeignKey(Technical, on_delete=models.CASCADE)
    start_time = models.DateField(blank=True, null=True)
    end_time = models.DateField(blank=True, null=True)
    def __str__(self):
         return self.technical.name

message/models.py
from django.db import models
import os, uuid

mylife/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.

class Aricletype(models.Model):
    type_name = models.CharField(max_length=30)
    number = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.type_name

class Lifenote(models.Model):
    aricletype = ForeignKey(Aricletype, on_delete=models.CASCADE)
    title_note = models.CharField(max_length=30)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=1000)
    praisecount = models.IntegerField(default=0)
    def __str__(self):
        return self.title_note

class CommentAricle(models.Model):
    content_comment = models.TextField(max_length=500)
    user_name = models.CharField(max_length=30)
    time = models.DateTimeField(auto_now_add=True)
    email = models.CharField(max_length=30)
    lifenote = ForeignKey(Lifenote, on_delete=models.CASCADE)
    parentcomment = models.ForeignKey('CommentAricle', blank=True, null=True, related_name='p_comment')

message/views.py
from django.shortcuts import render,render_to_response
from aboutme.models import Myself
import django_comments
def showmessage(request):
    myself = Myself.objects.all();
    if len(myself) > 0:
        return render(request, 'message.html', {'myselfInfo': myself[0]})
    return render(request, 'message.html')

templates/aricledetail.html
{% extends 'base.html' %}
{% block bodyleft %}
     <div class="card">
        <div class="card-block">
            <div class="row text-center">
                <label style="font-size: 20px;margin-top: 10px">{{ aricledetail.title_note }}</label>
            </div>
            <div class="collapse navbar-collapse" style="margin-top: 10px">
                <ul class="nav navbar-nav" style="font-size: 14px;color: #00bbff">
                    <li><i style="font-size: 16px;margin-right: 5px" class="pe-7s-ticket"></i>{{ aricledetail.aricletype }}</li>
                    <li style="margin-left: 20px"><i style="font-size: 16px;margin-right: 5px" class="pe-7s-stopwatch"></i>{{ aricledetail.created_on|date:"Y-m-d"  }}</li>
                    <li style="margin-left: 20px"><i style="font-size: 14px" >点赞：</i>{{ aricledetail.praisecount }}</li>
                    <li style="margin-left: 20px"><i style="font-size: 14px" >评论：</i>{{ commentmun }}</li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-11">
                   <p style="margin-left: 10px;margin-top: 10px">{{ aricledetail.content|linebreaksbr }}</p>
                </div>
            </div>
        </div>
     </div>
     <div class="card">
        <div class="card-block">
            <div class="row"><p style="font-size: 20px;margin-top: 10px;color: #45c0fd" class="text-center">评论栏</p></div>
            {% for list in commentlist %}
                <div class="row">
                    <div class="col-md-11" style="margin-left: 10px;margin-bottom: 10px">
                        <div style="border-top:1px dashed #c0c0c0;">
                            <a href="" style="margin-top: 5px" class="pull-right">回复</a>
                            <p style="font-size: 16px;margin-top: 5px">{{ list.user_name }}   {{ list.time|date:"Y-m-d" }}</p>
                            <p style="font-size: 14px">{{ list.content_comment }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <form action="/mylife/postcomment/" method="POST" class="form" id="login-form" autocomplete="off">
                <input sy type='hidden' name="aricleID" value={{ aricle_id }} />
            {% csrf_token %}
                 <div class="col-md-11" style="border-top:1px dashed #c0c0c0;margin-left: 10px;margin-bottom: 10px">
                 </div>
                <div class="row">
                     <div class="col-md-4 col-md-offset-1">
                        <div class="form-group">
                             <input type="username" name="username" required="required" class="form-control" placeholder="Your Name"/>
                        </div>
                    </div>
                    <div class="col-md-4 col-md-offset-2">
                        <div class="form-group">
                             <input type="email" name="email"  class="form-control" placeholder="Your email"/>
                        </div>
                    </div>
                    <div class="col-md-10 col-md-offset-1" style="margin-bottom: 10px">
                        <textarea class="form-control" required="required" name="comment" placeholder="随便说点吧，博主感谢您的友好评论！" rows="6"></textarea>
                    </div>
                    <div class="col-md-10 col-md-offset-1" style="margin-bottom: 10px">
                         <button class="btn btn-info btn-fill pull-right">评论</button>
                    </div>
                </div>
            </form>
        </div>
     </div>
{% endblock %}

templates/base.html
{% load i18n %}
{% load staticfiles %}
<html lang="en" {% block htmlattr %}{% endblock %}>
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="/static/images/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="../assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>{% block title %}欢迎来到王博的博客{% endblock %}</title>
	{% block description %}

	{% endblock %}

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/gsdk.css" %}" rel="stylesheet"/>
    <link href="{% static "css/webapp.css" %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
	{% block extra_head %}{% endblock %}

</head>
<body style="background-color: white">
   <nav class="navbar navbar-ct-azure navbar-icons" role="navigation-demo">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="#">{% block welcome_content %}欢迎来到王博的博客{% endblock %}</a>
        </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigation-example-2">
            {% block navcontent %}
          <ul class="nav navbar-nav navbar-right">
                <li>
                   <a href="/mylife/home/">
                        <i class="pe-7s-home"></i>
                        <p>生活笔记</p>
                    </a>
                </li>
{#                <li>#}
{#                   <a href="" >#}
{#                        <i class="pe-7s-study"></i>#}
{#                        <p>技术瞎谈</p>#}
{#                    </a>#}
{#                </li>#}
                <li>
                   <a href="/message/showmessage/" >
                        <i class="pe-7s-mail"></i>
                        <p>给我留言</p>
                    </a>
                </li>
                <li>
                   <a href="" >
                        <i class="pe-7s-credit"></i>
                        <p>赞助博主</p>
                    </a>
                </li>
                <li>
                   <a href="/aboutme/aboutme/" >
                        <i class="pe-7s-user"></i>
                        <p>关于自己</p>
                    </a>
                </li>
                </li>
           </ul>
            {% endblock %}
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block bodycontent %}
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% block bodyleft %}
                    {% endblock %}
                </div>
                <div class="col-md-4">
                    {% block bodyright %}
                        <div class="row">
                            <div class="card">
                                <div class="card-block">
                                    <div class="row">
                                        <div class="col-md-12 text-center">
                                            <img style="margin-top: 10px" width="100px" height="100px" src="/media/{{ myselfInfo.avatar }}" alt="Circle Image" class="img-circle">
                                        </div>
                                        <div class="row" style="margin-left: 20px">
                                            <div class="col-md-9">
                                                <p>姓名：{{ myselfInfo.user_name }}</p>
                                                <p>职业：{{ myselfInfo.job_post }}</p>
                                                <p>QQ ：{{ myselfInfo.qq_number }}</p>
                                                <p>学历 ：{{ myselfInfo.education_background }}</p>
                                                <p>大学 ：{{ myselfInfo.university }}</p>
                                                <p>工作时间 ：{{ myselfInfo.work_time|date:"Y-m-d" }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-block">
                                    <div class="row text-center">
                                        <label style="font-size: 16px;margin-top: 10px;">友情链接</label>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <p style="font-size: 14px;margin-left: 10px"><a target="view_window" href="http://www.cocoachina.com">CocoaChina</a></p>
                                            <p style="font-size: 14px;margin-left: 10px"> <a target="view_window" href="http://www.runoob.com/python/python-tutorial.html">Python菜鸟教程</a></p>
                                            <p style="font-size: 14px;margin-left: 10px"> <a target="view_window" href="http://blog.devtang.com">唐巧博客 (iOS)</a></p>
                                            <p style="font-size: 14px;margin-left: 10px"><a target="view_window" href="http://blog.csdn.net/leixiaohua1020/">雷霄骅专栏(FFMPEG)</a></p>
                                        </div>
                                        <div class="col-md-6 pull-right">
                                            <p style="font-size: 14px"><a target="view_window" href="http://code4app.qiniudn.com">Code4App(iOS源码库)</a></p>
                                            <p style="font-size: 14px"> <a target="view_window" href="http://weibo.com/2697914143/profile?topnav=1&wvr=6">新浪微博(关注我)</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endblock %}
                </div>
            </div>
        </div>
    {% endblock %}
</body>
<footer class="footer" style="background-color: lightgray;position:absolute;width: 100%;">
    <div class="container">
        <div class="social-area pull-right">
            <a class="btn btn-social btn-facebook btn-simple">
                <i class="fa fa-facebook-square"></i>
            </a>
            <a class="btn btn-social btn-twitter btn-simple">
                <i class="fa fa-twitter"></i>
            </a>
            <a class="btn btn-social btn-pinterest btn-simple">
                <i class="fa fa-pinterest"></i>
            </a>
        </div>
        <div class="copyright">
            &copy; 2017 Creative wangbo
        </div>
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}生活笔记{% endblock %}
{% block bodyleft %}
    {% for list in notelist %}
    <div class="card">
        <div class="card-block">
            <div class="row">
                <div class="col-md-8" style="color: #00bbff">
                   <label style="font-size: 16px;margin-left: 10px;margin-top: 5px"><a href="/mylife/aricledetail/?aricle_id={{ list.pk }}">{{ list.title_note }}</a></label>
                </div>
                <div class="col-md-4 pull-right">
                    <p style="margin-top: 5px">分类：{{ list.aricletype.type_name }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p style="margin-left: 10px;display: -webkit-box;-webkit-box-orient: vertical;-webkit-line-clamp: 3;overflow: hidden;">{{ list.content }}</p>
{#                                <p>{{ article.content|linebreaksbr }}</p> #}
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <p style="font-size: 14px;margin-left: 10px;">日期：{{ list.created_on|date:"Y-m-d H:i:s" }}</p>
                </div>
                <div>
                    <div class="col-md-4" style="color: #00bbff">
                         <p style="font-size: 14px;margin-left: 10px;">点赞（{{ list.praisecount }}）</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

templates/lifelist.html
{% extends 'base.html' %}

{% block bodycontent %}

{% endblock %}

templates/login.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="/static/images/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="../assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>{% block title %}博客后台管理{% endblock %}</title>
	{% block description %}

	{% endblock %}

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/gsdk.css" %}" rel="stylesheet"/>
    <link href="{% static "css/webapp.css" %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
	{% block extra_head %}{% endblock %}
</head>

<body>
    <div class="section section-gray">
        <div class="container" style="margin-top: 200px">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="card">
                        <div class="card-block">
                            <div class="row text-center">
                                <div><h4>博客后台管理</h4></div>
                            </div>
                            <div class="row">
                                <form action="/man/" method="POST" class="form" id="login-form" autocomplete="off">
                                {% csrf_token %}
                                <div class="col-md-8 col-md-offset-2">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i style="font-size: 20px" class="fa pe-7s-users"></i></span>
                                        <input  type="text" required="required" class="form-control" id="username" name="username" placeholder="{% trans "Account" %}" class="form-control">
                                    </div>
                                    <div style="margin-top: 10px" class="input-group">
                                        <span class="input-group-addon"><i style="font-size: 20px" class="fa pe-7s-unlock"></i></span>
                                        <input required="required" id="password" name="password" type="password" placeholder="{% trans "Password" %}" class="form-control">
                                    </div>
                                    {% if code %}
                                         <div class="row text-center"><label style="color: red">{{ code }}</label></div>
                                    {% endif %}
                                    <div style="margin-top: 10px">
                                        <button type="submit" class="form-actions btn btn-social btn-block btn-lg btn-fill btn-info">登录</button><br>
                                    </div>
                                 </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/message.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comments %}
{% block title %}给我留言{% endblock %}
{% block bodyleft %}

{{ comments }}

{#{% get_comment_form for post as form %}#}
{#<form action='{%comment_form_target%}' method='post'>#}
{#    {% csrf_token %}#}
{#    {{form.object_pk}}#}
{#    {{form.content_type}}#}
{#    {{form.timestamp}}#}
{#    {{form.security_hash}}#}
{#    <p><label for="id_name">姓名（必填）：</label><input name="name" id="id_name"></p>#}
{#    <p><label for="id_email">邮箱（必填）：</label><input name="email" id="id_email"></p>#}
{#    <p><label for="id_url">网站（可选）：</label><input name="url" id="id_url"></p>#}
{#    <p><label for="id_comment">评论（必填）：</label></p>#}
{#    <p><textarea id="id_comment" rows="10" cols="40" name="comment"></textarea></p>#}
{#    <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，那么你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>#}
{#    <p><input name="post" value="发表" type="submit" /></p>#}
{#    <input type='hidden' name='next' value='{%url post_by_id post.id%}'/>#}
{#</form>#}
{% endblock %}

templates/myself.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}关于自己{% endblock %}

{% block bodycontent %}
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-block">
                    <div class="row text-center">
                        <div><h4>关于自己</h4></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4 text-center">
{#                            <img src="{% static 'images/avatar/default-avatar.png' %}" alt="Circle Image" class="img-circle">#}
                            <img width="200px" height="200px" src="/media/{{ myselfInfo.avatar }}" alt="Circle Image" class="img-circle">
                        </div>
                    </div>
                    <div class="row" style="margin-top: 10px">
                        <div class="col-md-4 col-md-offset-4 text-center" style="color: #45c0fd;font-size: 18px">
                            {{ myselfInfo.user_name }}（{{ myselfInfo.introduce }}）
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3 text-center" style="font-size: 18px">
                            <p>{{ myselfInfo.content }}</p>
                        </div>
                    </div>
                    <div class="text-center" style="background-color: #f3f3f3">
                        <div><h4>技能列表</h4></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3"style="margin-bottom: 10px">
                            {% for tech in useTechniallist %}
                                <div class="row">
                                    <div class="col-md-3">
                                        <label style="font-size: 16px">{{ tech.technical.name }}</label>
                                    </div>
                                    <div class="col-md-9">
                                        {% if tech.end_time  %}
                                            {{ tech.start_time|date:"Y-m-d" }}~{{ tech.end_time|date:"Y-m-d" }}
                                        {% else %}
                                            {{ tech.start_time|date:"Y-m-d" }}~ 至今
                                        {% endif %}

                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pushlife.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>